{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 178,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import boto3\n",
    "import pandas as pd\n",
    "from io import StringIO, BytesIO\n",
    "from datetime import datetime, timedelta"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 180,
   "outputs": [],
   "source": [
    "# Environment Variables\n",
    "source_bucket = 'deutsche-boerse-xetra-pds'\n",
    "day_diff = 3\n",
    "cols = ['ISIN', 'Mnemonic', 'SecurityDesc',\n",
    "        'SecurityType', 'Currency',\n",
    "        'SecurityID', 'Date', 'Time', 'StartPrice', 'MaxPrice', 'MinPrice',\n",
    "        'EndPrice', 'TradedVolume']"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 184,
   "outputs": [],
   "source": [
    "def read_source(source_bucket):\n",
    "    s3 = boto3.resource('s3')\n",
    "    bucket = s3.Bucket(source_bucket)\n",
    "    return bucket\n",
    "def csv_to_df(bucket, day_diff):\n",
    "    df_all = pd.DataFrame(columns=cols)\n",
    "    arg_date_dt =datetime.today() - timedelta(days=day_diff)\n",
    "    objects = [o for o in bucket.objects.all() if datetime.strptime(o.key.split('/')[0], \"%Y-%m-%d\").date() >= arg_date_dt.date()]\n",
    "    for each in objects:\n",
    "        csv_obj_init = bucket.Object(key=each.key).get().get('Body').read().decode('utf-8')\n",
    "        dat = StringIO(csv_obj_init)\n",
    "        df = pd.read_csv(dat, delimiter=',')\n",
    "        df_all = df_all.append(df, ignore_index=True)\n",
    "    return df_all"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/nr/4jyzpsz56ts7c38jvfy1ktjw0000gn/T/ipykernel_19680/517554653.py\", line 1, in <module>\n",
      "    df_all = csv_to_df(bucket=read_source(source_bucket), day_diff=3)\n",
      "  File \"/var/folders/nr/4jyzpsz56ts7c38jvfy1ktjw0000gn/T/ipykernel_19680/587342521.py\", line 8, in csv_to_df\n",
      "    objects = [o for o in bucket.objects.all() if datetime.strptime(o.key.split('/')[0], \"%Y-%m-%d\").date() >= arg_date_dt.date()]\n",
      "  File \"/var/folders/nr/4jyzpsz56ts7c38jvfy1ktjw0000gn/T/ipykernel_19680/587342521.py\", line 8, in <listcomp>\n",
      "    objects = [o for o in bucket.objects.all() if datetime.strptime(o.key.split('/')[0], \"%Y-%m-%d\").date() >= arg_date_dt.date()]\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/boto3/resources/collection.py\", line 83, in __iter__\n",
      "    for page in self.pages():\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/boto3/resources/collection.py\", line 166, in pages\n",
      "    for page in pages:\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/paginate.py\", line 255, in __iter__\n",
      "    response = self._make_request(current_kwargs)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/paginate.py\", line 334, in _make_request\n",
      "    return self._method(**current_kwargs)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/client.py\", line 391, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/client.py\", line 705, in _make_api_call\n",
      "    http, parsed_response = self._make_request(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/client.py\", line 725, in _make_request\n",
      "    return self._endpoint.make_request(operation_model, request_dict)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/endpoint.py\", line 104, in make_request\n",
      "    return self._send_request(request_dict, operation_model)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/endpoint.py\", line 149, in _send_request\n",
      "    success_response, exception = self._get_response(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/endpoint.py\", line 167, in _get_response\n",
      "    success_response, exception = self._do_get_response(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/endpoint.py\", line 201, in _do_get_response\n",
      "    http_response = self._send(request)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/endpoint.py\", line 270, in _send\n",
      "    return self.http_session.send(request)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/httpsession.py\", line 385, in send\n",
      "    urllib_response = conn.urlopen(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 699, in urlopen\n",
      "    httplib_response = self._make_request(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 445, in _make_request\n",
      "    six.raise_from(e, None)\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 440, in _make_request\n",
      "    httplib_response = conn.getresponse()\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/http/client.py\", line 1371, in getresponse\n",
      "    response.begin()\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/http/client.py\", line 319, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/http/client.py\", line 280, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/socket.py\", line 704, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/ssl.py\", line 1241, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/ssl.py\", line 1099, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/inspect.py\", line 1541, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/inspect.py\", line 1499, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/inspect.py\", line 709, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/inspect.py\", line 738, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/inspect.py\", line 722, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/posixpath.py\", line 380, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/nr/4jyzpsz56ts7c38jvfy1ktjw0000gn/T/ipykernel_19680/517554653.py\", line 1, in <module>\n",
      "    df_all = csv_to_df(bucket=read_source(source_bucket), day_diff=3)\n",
      "  File \"/var/folders/nr/4jyzpsz56ts7c38jvfy1ktjw0000gn/T/ipykernel_19680/587342521.py\", line 8, in csv_to_df\n",
      "    objects = [o for o in bucket.objects.all() if datetime.strptime(o.key.split('/')[0], \"%Y-%m-%d\").date() >= arg_date_dt.date()]\n",
      "  File \"/var/folders/nr/4jyzpsz56ts7c38jvfy1ktjw0000gn/T/ipykernel_19680/587342521.py\", line 8, in <listcomp>\n",
      "    objects = [o for o in bucket.objects.all() if datetime.strptime(o.key.split('/')[0], \"%Y-%m-%d\").date() >= arg_date_dt.date()]\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/boto3/resources/collection.py\", line 83, in __iter__\n",
      "    for page in self.pages():\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/boto3/resources/collection.py\", line 166, in pages\n",
      "    for page in pages:\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/paginate.py\", line 255, in __iter__\n",
      "    response = self._make_request(current_kwargs)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/paginate.py\", line 334, in _make_request\n",
      "    return self._method(**current_kwargs)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/client.py\", line 391, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/client.py\", line 705, in _make_api_call\n",
      "    http, parsed_response = self._make_request(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/client.py\", line 725, in _make_request\n",
      "    return self._endpoint.make_request(operation_model, request_dict)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/endpoint.py\", line 104, in make_request\n",
      "    return self._send_request(request_dict, operation_model)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/endpoint.py\", line 149, in _send_request\n",
      "    success_response, exception = self._get_response(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/endpoint.py\", line 167, in _get_response\n",
      "    success_response, exception = self._do_get_response(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/endpoint.py\", line 201, in _do_get_response\n",
      "    http_response = self._send(request)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/endpoint.py\", line 270, in _send\n",
      "    return self.http_session.send(request)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/httpsession.py\", line 385, in send\n",
      "    urllib_response = conn.urlopen(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 699, in urlopen\n",
      "    httplib_response = self._make_request(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 445, in _make_request\n",
      "    six.raise_from(e, None)\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 440, in _make_request\n",
      "    httplib_response = conn.getresponse()\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/http/client.py\", line 1371, in getresponse\n",
      "    response.begin()\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/http/client.py\", line 319, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/http/client.py\", line 280, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/socket.py\", line 704, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/ssl.py\", line 1241, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/ssl.py\", line 1099, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3364, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3461, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2066, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/inspect.py\", line 1541, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/inspect.py\", line 1499, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/inspect.py\", line 709, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/inspect.py\", line 738, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/inspect.py\", line 722, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/posixpath.py\", line 380, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/nr/4jyzpsz56ts7c38jvfy1ktjw0000gn/T/ipykernel_19680/517554653.py\", line 1, in <module>\n",
      "    df_all = csv_to_df(bucket=read_source(source_bucket), day_diff=3)\n",
      "  File \"/var/folders/nr/4jyzpsz56ts7c38jvfy1ktjw0000gn/T/ipykernel_19680/587342521.py\", line 8, in csv_to_df\n",
      "    objects = [o for o in bucket.objects.all() if datetime.strptime(o.key.split('/')[0], \"%Y-%m-%d\").date() >= arg_date_dt.date()]\n",
      "  File \"/var/folders/nr/4jyzpsz56ts7c38jvfy1ktjw0000gn/T/ipykernel_19680/587342521.py\", line 8, in <listcomp>\n",
      "    objects = [o for o in bucket.objects.all() if datetime.strptime(o.key.split('/')[0], \"%Y-%m-%d\").date() >= arg_date_dt.date()]\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/boto3/resources/collection.py\", line 83, in __iter__\n",
      "    for page in self.pages():\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/boto3/resources/collection.py\", line 166, in pages\n",
      "    for page in pages:\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/paginate.py\", line 255, in __iter__\n",
      "    response = self._make_request(current_kwargs)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/paginate.py\", line 334, in _make_request\n",
      "    return self._method(**current_kwargs)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/client.py\", line 391, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/client.py\", line 705, in _make_api_call\n",
      "    http, parsed_response = self._make_request(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/client.py\", line 725, in _make_request\n",
      "    return self._endpoint.make_request(operation_model, request_dict)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/endpoint.py\", line 104, in make_request\n",
      "    return self._send_request(request_dict, operation_model)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/endpoint.py\", line 149, in _send_request\n",
      "    success_response, exception = self._get_response(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/endpoint.py\", line 167, in _get_response\n",
      "    success_response, exception = self._do_get_response(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/endpoint.py\", line 201, in _do_get_response\n",
      "    http_response = self._send(request)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/endpoint.py\", line 270, in _send\n",
      "    return self.http_session.send(request)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/botocore/httpsession.py\", line 385, in send\n",
      "    urllib_response = conn.urlopen(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 699, in urlopen\n",
      "    httplib_response = self._make_request(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 445, in _make_request\n",
      "    six.raise_from(e, None)\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 440, in _make_request\n",
      "    httplib_response = conn.getresponse()\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/http/client.py\", line 1371, in getresponse\n",
      "    response.begin()\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/http/client.py\", line 319, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/http/client.py\", line 280, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/socket.py\", line 704, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/ssl.py\", line 1241, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/ssl.py\", line 1099, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3364, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3461, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2066, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2947, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3172, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3383, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2066, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/inspect.py\", line 1541, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/inspect.py\", line 1499, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/inspect.py\", line 709, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/inspect.py\", line 738, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/inspect.py\", line 722, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/Users/kaleynguyen/opt/anaconda3/envs/.venv/lib/python3.9/posixpath.py\", line 380, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n"
     ]
    }
   ],
   "source": [
    "df_all = csv_to_df(bucket=read_source(source_bucket), day_diff=3)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n",
     "is_executing": true
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 187,
   "outputs": [],
   "source": [
    "# Get opening price per ISIN and day\n",
    "df_all['opening_price'] = df_all.sort_values(by=['Time']).groupby(['ISIN', 'Date'])['StartPrice'].transform('first')\n",
    "# Get closing price per ISIN and day\n",
    "df_all['closing_price'] = df_all.sort_values(by=['Time']).groupby(['ISIN', 'Date'])['StartPrice'].transform('last')\n",
    "# Perform aggregation per each (ISIN,Date)\n",
    "df_all = df_all.groupby(['ISIN', 'Date'], as_index=False).\\\n",
    "    agg({\n",
    "                'opening_price': 'min',\n",
    "                'closing_price': 'min',\n",
    "                'MinPrice': 'min',\n",
    "                'MaxPrice': 'max',\n",
    "                'TradedVolume': 'sum'\n",
    "}).rename(\n",
    "    columns = { 'opening_price': 'opening_price_eur',\n",
    "                'closing_price': 'closing_price_eur',\n",
    "                'MinPrice': 'minimum_price_eur',\n",
    "                'MaxPrice': 'max_price_eur',\n",
    "                'TradedVolume': 'daily_traded_volume'\n",
    "}\n",
    ")\n",
    "\n",
    "# Compute percent change prev closing\n",
    "df_all['prev_closing_price'] = df_all.sort_values('Date').groupby(['ISIN'])['closing_price_eur'].shift(1) #lag(1)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 188,
   "outputs": [
    {
     "data": {
      "text/plain": "           ISIN        Date  opening_price_eur  closing_price_eur  \\\n0  AT000000STR1  2022-03-25              36.80              36.40   \n1  AT000000STR1  2022-03-28              36.95              36.85   \n2  AT00000FACC2  2022-03-25               7.83               7.92   \n3  AT00000FACC2  2022-03-28               8.16               8.16   \n4  AT0000606306  2022-03-25              12.39              12.53   \n\n   minimum_price_eur  max_price_eur  daily_traded_volume  prev_closing_perc  \n0              36.40          36.80                  119                NaN  \n1              36.75          37.00                  260               1.22  \n2               7.83           7.92                   74                NaN  \n3               8.16           8.16                   50               2.94  \n4              12.32          12.77                19227                NaN  ",
      "text/html": "<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>ISIN</th>\n      <th>Date</th>\n      <th>opening_price_eur</th>\n      <th>closing_price_eur</th>\n      <th>minimum_price_eur</th>\n      <th>max_price_eur</th>\n      <th>daily_traded_volume</th>\n      <th>prev_closing_perc</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>AT000000STR1</td>\n      <td>2022-03-25</td>\n      <td>36.80</td>\n      <td>36.40</td>\n      <td>36.40</td>\n      <td>36.80</td>\n      <td>119</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>AT000000STR1</td>\n      <td>2022-03-28</td>\n      <td>36.95</td>\n      <td>36.85</td>\n      <td>36.75</td>\n      <td>37.00</td>\n      <td>260</td>\n      <td>1.22</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>AT00000FACC2</td>\n      <td>2022-03-25</td>\n      <td>7.83</td>\n      <td>7.92</td>\n      <td>7.83</td>\n      <td>7.92</td>\n      <td>74</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>AT00000FACC2</td>\n      <td>2022-03-28</td>\n      <td>8.16</td>\n      <td>8.16</td>\n      <td>8.16</td>\n      <td>8.16</td>\n      <td>50</td>\n      <td>2.94</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>AT0000606306</td>\n      <td>2022-03-25</td>\n      <td>12.39</td>\n      <td>12.53</td>\n      <td>12.32</td>\n      <td>12.77</td>\n      <td>19227</td>\n      <td>NaN</td>\n    </tr>\n  </tbody>\n</table>\n</div>"
     },
     "execution_count": 188,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_all['prev_closing_perc'] = (df_all['closing_price_eur'] - df_all['prev_closing_price'])/df_all['closing_price_eur']*100\n",
    "df_all = df_all.drop(columns=['prev_closing_price'])\n",
    "df_all = df_all.round(decimals=2)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 189,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2021-11-03 14:33:54 destination-snowflake\r\n",
      "2022-03-27 11:33:16 destination-xetra\r\n",
      "2021-12-15 13:45:47 lending-club\r\n",
      "2022-03-25 20:37:36 source-covid-19-jobs\r\n",
      "2021-11-03 14:33:28 source-snowflake\r\n",
      "2021-11-02 22:08:15 xetra-target\r\n"
     ]
    },
    {
     "data": {
      "text/plain": "s3.Object(bucket_name='destination-xetra', key='xetra_daily_report_20220328_141724.parquet')"
     },
     "execution_count": 189,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Save to S3\n",
    "!aws s3 ls\n",
    "key = 'xetra_daily_report_' + datetime.today().strftime('%Y%m%d_%H%M%S') + '.parquet'\n",
    "out_buffer = BytesIO()\n",
    "df_all.to_parquet(out_buffer, index=False)\n",
    "bucket_target = boto3.resource('s3').Bucket('destination-xetra')\n",
    "bucket_target.put_object(Body=out_buffer.getvalue(), Key=key)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 191,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "xetra_daily_report_20220327_115215.parquet\n",
      "xetra_daily_report_20220328_141724.parquet\n"
     ]
    },
    {
     "data": {
      "text/plain": "              ISIN        Date  opening_price_eur  closing_price_eur  \\\n0     AT000000STR1  2022-03-25              36.80              36.40   \n1     AT000000STR1  2022-03-28              36.95              36.85   \n2     AT00000FACC2  2022-03-25               7.83               7.92   \n3     AT00000FACC2  2022-03-28               8.16               8.16   \n4     AT0000606306  2022-03-25              12.39              12.53   \n...            ...         ...                ...                ...   \n6491  XS2427474023  2022-03-28              21.32              20.95   \n6492  XS2434891219  2022-03-25               3.98               4.05   \n6493  XS2434891219  2022-03-28               4.28               4.33   \n6494  XS2437455608  2022-03-25              24.71              24.06   \n6495  XS2437455608  2022-03-28              24.51              24.30   \n\n      minimum_price_eur  max_price_eur  daily_traded_volume  prev_closing_perc  \n0                 36.40          36.80                  119                NaN  \n1                 36.75          37.00                  260               1.22  \n2                  7.83           7.92                   74                NaN  \n3                  8.16           8.16                   50               2.94  \n4                 12.32          12.77                19227                NaN  \n...                 ...            ...                  ...                ...  \n6491              20.95          21.32                    0              -3.40  \n6492               3.96           4.08                14832                NaN  \n6493               4.28           4.33               126408               6.38  \n6494              24.06          24.71                    0                NaN  \n6495              24.30          24.51                    0               0.96  \n\n[6496 rows x 8 columns]",
      "text/html": "<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>ISIN</th>\n      <th>Date</th>\n      <th>opening_price_eur</th>\n      <th>closing_price_eur</th>\n      <th>minimum_price_eur</th>\n      <th>max_price_eur</th>\n      <th>daily_traded_volume</th>\n      <th>prev_closing_perc</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>AT000000STR1</td>\n      <td>2022-03-25</td>\n      <td>36.80</td>\n      <td>36.40</td>\n      <td>36.40</td>\n      <td>36.80</td>\n      <td>119</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>AT000000STR1</td>\n      <td>2022-03-28</td>\n      <td>36.95</td>\n      <td>36.85</td>\n      <td>36.75</td>\n      <td>37.00</td>\n      <td>260</td>\n      <td>1.22</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>AT00000FACC2</td>\n      <td>2022-03-25</td>\n      <td>7.83</td>\n      <td>7.92</td>\n      <td>7.83</td>\n      <td>7.92</td>\n      <td>74</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>AT00000FACC2</td>\n      <td>2022-03-28</td>\n      <td>8.16</td>\n      <td>8.16</td>\n      <td>8.16</td>\n      <td>8.16</td>\n      <td>50</td>\n      <td>2.94</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>AT0000606306</td>\n      <td>2022-03-25</td>\n      <td>12.39</td>\n      <td>12.53</td>\n      <td>12.32</td>\n      <td>12.77</td>\n      <td>19227</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>6491</th>\n      <td>XS2427474023</td>\n      <td>2022-03-28</td>\n      <td>21.32</td>\n      <td>20.95</td>\n      <td>20.95</td>\n      <td>21.32</td>\n      <td>0</td>\n      <td>-3.40</td>\n    </tr>\n    <tr>\n      <th>6492</th>\n      <td>XS2434891219</td>\n      <td>2022-03-25</td>\n      <td>3.98</td>\n      <td>4.05</td>\n      <td>3.96</td>\n      <td>4.08</td>\n      <td>14832</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>6493</th>\n      <td>XS2434891219</td>\n      <td>2022-03-28</td>\n      <td>4.28</td>\n      <td>4.33</td>\n      <td>4.28</td>\n      <td>4.33</td>\n      <td>126408</td>\n      <td>6.38</td>\n    </tr>\n    <tr>\n      <th>6494</th>\n      <td>XS2437455608</td>\n      <td>2022-03-25</td>\n      <td>24.71</td>\n      <td>24.06</td>\n      <td>24.06</td>\n      <td>24.71</td>\n      <td>0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>6495</th>\n      <td>XS2437455608</td>\n      <td>2022-03-28</td>\n      <td>24.51</td>\n      <td>24.30</td>\n      <td>24.30</td>\n      <td>24.51</td>\n      <td>0</td>\n      <td>0.96</td>\n    </tr>\n  </tbody>\n</table>\n<p>6496 rows × 8 columns</p>\n</div>"
     },
     "execution_count": 191,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Read the uploaded files\n",
    "for obj in bucket_target.objects.all():\n",
    "    print(obj.key)\n",
    "prq_obj = bucket_target.Object(key='xetra_daily_report_20220328_141724.parquet').get().get('Body').read()\n",
    "data = BytesIO(prq_obj)\n",
    "df_report = pd.read_parquet(data)\n",
    "df_report"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}